baseURL = "https://example.org/"
copyright = 'Copyright Â© {year} Fachschaft Informatik'
pluralizeListTitles = false
enableEmoji = true

defaultContentLanguage = "de"

params.onlyHeadings = ["protokolle"]

[params.socials.instagram]
url = "https://www.instagram.com/hhufscs/"
icon = "icons/brand-instagram.svg"

[params.socials.github]
url = "https://github.com/fscsk"
icon = "icons/brand-github.svg"



# languages
[languages.de]
languageName = "Deutsch"
title = "Fachschaft Informatik"
languageCode = "de"
languageDirection = "ltr"

[languages.en]
languageName = "English"
title = "Faculty Computer Science"
languageCode = "en"
languageDirection = "ltr"

# menus
[[menus.main]]
name = "Home"
weight = -1
pageRef = "/"
params = { icon = "icons/home.svg" }

[[menus.main]]
name = "Protokolle"
weight = 1
pageRef = "/protokolle"
params = { icon = "icons/script.svg" }

# menus
[[menus.main]]
name = "About"
weight = 100
pageRef = "/about"
params = { icon = "icons/question-mark.svg" }

[[menus.main]]
name = "News"
weight = 2
pageRef = "/news"
params = { icon = "icons/news.svg" }
