# Diese Datei definiert das deutsche Menü der Website.
# Die Einträge sind nach der Reihenfolge zu sortieren nach der sie auch auf der Website
# auftauchen sollen und Oberpunkte sind mit einem Kommentar zu markieren.
# ES IST EXTREM WICHTIG DAS SIE MIT DER DEUTSCHEN VERSION ÜBEREINSTIMMT

[[main]]
identifier = "home"
weight = 1
pageRef = "/"

[main.params]
icon = "icons/outline/home.svg"
disableCms = true

#--------------------------------------------------------------------------------------------------
# Klausurarchiv
#--------------------------------------------------------------------------------------------------

[[main]]
identifier = "examarchive"
weight = 2
pageRef = "/klausurarchiv"

[main.params]
icon = "icons/outline/school.svg"
disableCms = true

#--------------------------------------------------------------------------------------------------
# Protokolle
#--------------------------------------------------------------------------------------------------
[[main]]
name = "Protokolle"
identifier = "transcripts"
weight = 3
pageRef = "/protokolle"

[main.params]
icon = "icons/outline/script.svg"

[main.params.cms]
folder = "demo/content/protokolle"
slug = "{{year}}-{{month}}-{{day}}-protokoll"

#--------------------------------------------------------------------------------------------------
# Erstsemester 
#--------------------------------------------------------------------------------------------------
[[main]]
identifier = "firstsemester"
weight = 4
pageRef = "/studienanfaenger"

[main.params]
icon = "icons/outline/checkup-list.svg"
makeSingleton = true
cms = { folder = "demo/content/studienanfaenger" }
toplevelFile = { file = "demo/content/studienanfaenger.{{locale}}.md" }

[[main]]
identifier = "getting-started"
weight = 1
parent = "firstsemester"
pageRef = "/studienanfaenger/getting-started"

[[main]]
identifier = "esag"
weight = 2
parent = "firstsemester"
pageRef = "/studienanfaenger/esag"

[[main]]
identifier = "links"
weight = 3
parent = "firstsemester"
pageRef = "/studienanfaenger/wichtige-links"

[[main]]
identifier = "social-media"
weight = 4
parent = "firstsemester"
pageRef = "/studienanfaenger/social-media"

[[main]]
identifier = "ersti-faq"
weight = 5
parent = "firstsemester"
pageRef = "/studienanfaenger/faq"


#--------------------------------------------------------------------------------------------------
# FAQ
#--------------------------------------------------------------------------------------------------

[[main]]
identifier = "faq"
weight = 7
pageRef = "/faq"

[main.params]
icon = "icons/outline/message.svg"
cms = { folder = "demo/content/faq" }

[[main]]
identifier = "erstisticks"
weight = 1
parent = "faq"
pageRef = "/faq/erstisticks"

[[main]]
identifier = "abschlussarbeit"
weight = 2
parent = "faq"
pageRef = "/faq/abschlussarbeit"

#--------------------------------------------------------------------------------------------------
# About Us
#--------------------------------------------------------------------------------------------------

[[main]]
identifier = "aboutus"
weight = 1337
pageRef = "/aboutus"

[main.params]
icon = "icons/outline/question-mark.svg"
cms = { folder = "demo/content/aboutus" }
